---
- name: Install docker
  apt:
    name: docker.io
    state: latest

- name: Usermod
  command: usermod -aG docker dev
  register: command_result
  ignore_errors: True

- name: fail the play if the previous command did not succeed
  fail: msg="the command failed"
  when: "'FAILED' in command_result.stderr"

- name: Create docker service folder
  file: state=directory path={{docker_service_folder}} owner=dev group=dev recurse=yes

- name: Install Compose on Ubuntu systems
  shell: "curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose"
  args:
  warn: no

- name: Apply executable permissions to the binary
  command: "{{ item }}"
  with_items:
    - chmod +x /usr/local/bin/docker-compose
    - systemctl daemon-reload

- name: restart docker
  service:
    name: docker
    state: restarted
